name: CI - Laravel Checks

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Optional: add lightweight code checks here (linting, formatting)
      # Example:
      # - name: PHP Code Sniffer
      #   run: composer phpcs
