name: CD - Laravel Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying branch ${GITHUB_REF##*/}..."

            if [ "${GITHUB_REF##*/}" = "develop" ]; then
              cd /var/www/dexora-staging
              git fetch origin
              git checkout develop
              git reset --hard origin/develop
            elif [ "${GITHUB_REF##*/}" = "main" ]; then
              cd /var/www/dexora-production
              git fetch origin
              git checkout main
              git reset --hard origin/main
            fi

            # Run PHP commands on server
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "✅ Deployment complete. Run 'php artisan migrate --force' manually if database changes are required."
