name: CD - Laravel Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ "${{ github.ref_name }}" = "develop" ]; then
              cd /var/www/dexora-staging
              git pull origin develop
            elif [ "${{ github.ref_name }}" = "main" ]; then
              cd /var/www/dexora-production
              git pull origin main
            fi

            # Run PHP commands on server (server already has PHP/Composer)
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Deployment complete. Run 'php artisan migrate --force' manually if database changes are required."
